### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by CAH-MohanRao** [bssunil046/FlutterTestApp#1]
I downloaded the zip file and ran the app from my IDE. It throws following error.  

5.10.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
5.10.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
5.10.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
*** First throw call stack:

**Comment by bssunil046** [comment]
@CAH-MohanRao The issue was because of the firebase-database.  I have removed it from pubspec.yaml.  We are using REST API for firebase database operation.  Please update the code and confirm if its working.
